### ISSUE TITLE
packages = ['lxdock'] without subpackages will become a problem when doing debian packaging

### ISSUE THREAD

**Issue by robvdl** [lxdock/lxdock#100]
I know I have mentioned this before and I got the answer back that "it works".

However I have to disagree here, when you have packages = ['lxdock'] in a setup.py, you really MUST include subpackages, if you don't it will not package properly into a deb.

So it should be packages = ['lxdock', 'lxdock.guests', 'lxdock.hosts', ....]

I want to make lxdock into a deb one day, so I am just mentioning this now, it definitely will become a problem when doing debian packaging.

There is a reason why find_packages() is normally used in the setup.py, and that is why.

Also, similarly the MANIFEST.in must be properly defined for debian packaging, or it may end up missing out on static files or templates for example.  These tend to be common issues that surface when doing debian packaging.

**Comment by hsoft** [comment]
@robvdl I should have listened to you better. The v0.4.0 release is broken because of this. Creating a v0.4.1 one...

**Comment by hsoft** [comment]
What files are missing the the MANIFEST.in for debian packaging to work properly?

**Comment by robvdl** [comment]
@hsoft I had a look at this project and the MANIFEST.in file won't be an issue here, it's not applicable because there are only code subfolders in lxdock folder, not templates or static files etc.

So should be OK to close this issue.
