### ISSUE TITLE
support for snap lxd

### ISSUE THREAD

**Issue by battlemidget** [lxdock/lxdock#103]
Workaround:

```
LXD_DIR=/var/snap/lxd/common/lxd lxdock up
```

Would be nice to pass in an option in `.lxdock.yml` to specify either `LXD_DIR` or that you are running a snap version of lxd since eventually this will be the preferred way of installing lxd.

**Comment by hsoft** [comment]
@battlemidget considering that this option is environment-specific rather than project-specific, isn't `.env` better suited for this kind of option?

**Comment by battlemidget** [comment]
At the very least I would think lxdock could possibly check for the existence of snap lxd? With 18.04 around the corner and snaps being pushed heavily it may be worth supporting snaps early on to iron out any possible initial user experience problems.

**Comment by hsoft** [comment]
lxdock relies on pylxd for finding the proper path for the unix socket to connect to and it looks like [snap support was added recently](https://github.com/lxc/pylxd/blob/master/pylxd/client.py#L246). We just have to wait for a pylxd release and everything should be alright.

**Comment by robvdl** [comment]
fixed
