### ISSUE TITLE
lxdock shell -c "command" in quotes produces strange error

### ISSUE THREAD

**Issue by robvdl** [lxdock/lxdock#129]
Without quotes:

    $ lxdock shell -c ls /
    bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  src  srv  sys  tmp  usr  va

With quotes:

    $ lxdock shell -c "ls /"
    /.lxdock.d/shell_cmd.sh: 2: /.lxdock.d/shell_cmd.sh: ls /: not found

**Comment by robvdl** [comment]
Also this is a bit scary:

This command

    lxdock shell -c cd /tmp; pwd

Does not run pwd on the container but on the host.

Because I can't put quotes around it due to this issue, I can't find a nice way to run two commands like change directory and run a build for example.

I think when this feature got added there were a few issues around it, it doesn't quite seem to work right.

**Comment by shuhaowu** [comment]
Looking at the `Container.shell` code it looks like it's expecting a list of cmd args. Seems like this behaviour should be changed to taking a shell string.

**Comment by robvdl** [comment]
The shell method has mutable default arguments too.

**Comment by robvdl** [comment]
It seems the shlex.quote is doing it. It's wrapping it in single quotes so it's 'command1; command2' and then puts that in a shell script which it uploads.

I wonder if I strip the quotes that will be a good enough fix, but then I wonder why it needs to run through shlex.quote at all, I'm not even sure why it's needed.

**Comment by robvdl** [comment]
I've looked at this a few times and my only conclusion is that running each argument shlex.quote is not needed and actually breaks things. @shuhaowu what do you think?

If we were to make this the same as Vagrant all you have to do is remove the shlex.quote and it behaves as you would expect.

    lxdock shell -c "command1; command2; command3"

But the minute I run things through shlex.quote it ends up creating a bash script like this:

    #!/bin/sh
    'command1; command2; command3'

The shlex.quote is wrapping the entire thing in single quotes, I just don't think it's doing the right thing here. and needs to be taken out.

**Comment by shuhaowu** [comment]
From the python documentation:

>  `shlex.quote(s)`

>    Return a shell-escaped version of the string s. The returned value is a string that can safely be **used as one token in a shell** command line, for cases where you cannot use a list.

I'm not quite sure if shlex.quote is ever needed when we try to execute the command by first writing it into a file as it is defined for wrapping commands so it can be safely executed via a shell. Perhaps the code was a left over from the days when we were not executing the command fromw within a script but rather directly from the shell command line.

**Comment by robvdl** [comment]
I'll create a PR and remove that call to shlex.quote then, I thought so too.

I'll also fix that mutable default argument because it's in the same function and I just noticed it.

**Comment by robvdl** [comment]
It looks like the initial intention was that they were running multiple commands line this:

    lxdock shell -c command1 command2

or

    lxdock shell -c "command1" "command2"

But both of those are a bit odd syntax wise and not how Vagrant works, it would be something like this instead:

    lxdock shell -c "command1; command2"

I am putting up a PR where both are still supported by splitting multiple cmd_args to newlines in the shell script it creates.  That way if you use "command1; command2" it will be one on line, but if you use the old syntax it will split it over multiple lines and still work.

**Comment by robvdl** [comment]
There are 2 tests failing because they are testing the old syntax and automatic quoting of each arg.

I feel I need to remove these tests as it's testing behaviour that is no longer valid.

I just feel that lxdock shell -c "command1; command2; command3" is the right syntax and Vagrant works this way.

I think that lxdock shell -c command1 command2 command3 and have it auto quote things is really strange.

**Comment by robvdl** [comment]
In fact Vagrant is quite strict and they only allow the way I suggested, this works:

    vagrant ssh -c "ls -la"

This does not work with Vagrant, and this is the way that lxdock is doing it currently:

    vagrant ssh -c ls -la

I think, like Vagrant, we should error out here rather than attempt to parse that onto individual lines, as that is bound to go wrong.

That means we technically should only be checking for 1 argument after -c, any additional arguments is an error.
