### ISSUE TITLE
Travis broken???

### ISSUE THREAD

**Issue by robvdl** [lxdock/lxdock#149]
After merging the latest commit, I got an email that the travis build broke.

But I no longer see anything here https://travis-ci.com/lxdock/lxdock, I am getting "we couldn't find the repository lxdock/lxdock"

**Comment by robvdl** [comment]
@hsoft since I am a maintainer but not owner, can you maybe see the travis lxdock project?

**Comment by robvdl** [comment]
I think this has to do with the recent github app integration upgrade travis ci did, where you can now manage both open source and private projects or something like that.

However it seems after this I can no longer see lxdock/lxdock on travis.

Hopefully it's just an easy fix.

**Comment by hsoft** [comment]
@robvdl I made you an owner.

**Comment by robvdl** [comment]
Should be fixed now, had to play around a bit to get it back.

It's running a job now for master, will close this issue once it finishes.

**Comment by robvdl** [comment]
What confused me is two different domains, travis-ci.org and travis-ci.com, since I also have a number of private repos I work on I was looking on travis-ci.com

**Comment by shuhaowu** [comment]
I believe .org merged into .com
