### ISSUE TITLE
Travis tests very slow and time out, LXD 3 release related?

### ISSUE THREAD

**Issue by robvdl** [lxdock/lxdock#154]
First of all, it seems that the latest snap of lxd already creates the network bridge, so this part needs to be removed from the ci-base-setup script.

However, in doing so the tests are now hanging and eventually timing out after 10 mins in Travis CI.

**Comment by robvdl** [comment]
It appears that the tests are running, it's just very slow to get responses from lxd making the tests run very slow and eventually time out in Travis CI but seem to be fine in a local Vagrant VM.

I'm looking into this, appears to be an lxd 3.x issue.

**Comment by robvdl** [comment]
Appears to be related to this: https://github.com/lxc/lxd/issues/4548

**Comment by robvdl** [comment]
I am wondering if in the mean time, the developer merging a commit should run the tests in a local vagrant in the mean time.  It's not ideal, but it could take a while before lxd gets fixed.

**Comment by shuhaowu** [comment]
Might be related to this: #316

We should pin the version of pylxd to anything BUT 2.2.7 for now.

**Comment by robvdl** [comment]
oh cool, thanks for that, will look into this.

**Comment by robvdl** [comment]
Yes this seems to be the case, I have pinned pylxd so it won't install 2.2.7

We can probably remove the pin once 2.2.8 has been been released.

I'm going to merged this now so that CI is working again.

**Comment by robvdl** [comment]
Fixed
