### ISSUE TITLE
Do we have any option to start the containers in serial and not parallel?

### ISSUE THREAD

**Issue by justmeandopensource** [lxdock/lxdock#162]
Created a lxdock.yaml file with few containers. I would like to start the containers one by one as each one depends on the previous one. 
In Vagrant we have an option like --no-parallel. Is there anything equivalent?

Thanks,
Venkat

**Comment by robvdl** [comment]
Hi, at the moment lxdock is barely maintained as I have started using docker-compose I no longer have need for lxdock, I think we're just down to 1 or 2 developers who are both quite busy on other projects, the project hasn't really moved for a few months now. Unless you're willing to add this functionality yourself as a PR, I don't see this being added due to the lack of manpower right now.

**Comment by robvdl** [comment]
I know this answer sounds quite grim sorry, but I just like to state things how they really are. There are a number of outstanding issues like #161, #147 just to list a few and my effort towards a 0.5 release have basically stalled. See #122, #133, and also about the state of the project see #106 / #109

**Comment by justmeandopensource** [comment]
No problem. Thanks for this work. I find it very useful for my case even in its current state.

**Comment by robvdl** [comment]
With docker compoose you would basically do this with container dependencies, e.g. the "web" container is dependent on the "db" and "redis" container, so it must start the db and redis container first.

**Comment by justmeandopensource** [comment]
Yeah I have been using docker-compose for a long time. But it won't help for lxd containers, will it?

**Comment by robvdl** [comment]
No but it's just a suggestion how it could be implemented.

**Comment by justmeandopensource** [comment]
Yeah. Thanks.

**Comment by bmullan** [comment]
There are some other projects tho.  Like

https://github.com/turtle0x1/LxdManager

**Comment by justmeandopensource** [comment]
Thanks. I will take a look.

**Comment by bmullan** [comment]
There is also openstack & opennebula
