### ISSUE TITLE
Add a "nomad" user by default

### ISSUE THREAD

**Issue by ellmetha** [lxdock/lxdock#21]
We could decide to create a "nomad" user on each container created using lxd-nomad and automatically use this user when doing `nomad shell` (unless something else is specified with the ``shell`` option). Basically this "nomad" user would have access to shared folders and could be allowed to use "sudo" without limitation.

Additionally we could add an option ``create_nomad_user`` (which would default to ``true``) in the YML config file. This option would define whether or not this user should be created. :wink:

@hsoft what are your thoughts on this?

**Comment by hsoft** [comment]
It's certainly a problem to manage shared folders access to users in unprivileged containers. #19 did a good first step and I like the approach.

Fiddling I've been doing here indicates that we shouldn't even try to set ACLs from within the container, I always get "Malformed ACL" errors.

However, I don't understand the need for sudo configuration. If some user needs sudo access, ansible provisioning should be more than enough to manage that. I'm under the impression that doing like vagrant and providing a "nomad" gateway user needlessly complicates thing. Why not use root directly?

As for facilitating access to shared folders for non-root users in the container, the first approach I'd try would be this:

* Have a new `users` preference that is a list of users that nomad creates (or ensure that they're created) on launch.
* Make sure that these users have home directories.
* From the host, find the `home/{{ username }}` folder of the container. That folder belongs to our user
* Use a similar mechanism than what we've done in #19 to ensure that this user has ACLs to our shared folders.
* Profit!?

**Comment by ellmetha** [comment]
Your proposal sounds good. We could start by adding this ``users`` option. But I think that we could allow something like this too:

```
users:
  - name: testuser01
    sudo: yes
  - name: testuser02
```
But let's keep this idea for another time. :wink:

**Comment by ellmetha** [comment]
I'll close this issue because the `users` option is now part of LXDock. Regarding the `sudo` use case, this can be addressed using a provisioning tool.
