### ISSUE TITLE
Add support for new guests

### ISSUE THREAD

**Issue by ellmetha** [lxdock/lxdock#29]
* Alpine
* Centos
* Fedora
* Gentoo
* opensuse
* ...

LXDock uses the container images listed at https://images.linuxcontainers.org/ by default.

**Comment by lingxiaoyang** [comment]
A problem noted while implementing Alpine: 

Alpine doesn't have `bash` so `lxdock shell` doesn't respond. The command is `ash`.

Possible solutions. Which do you think is better?
1. install `bash` when setting up Alpine.
2. Make it possible to provide the command to execute for `lxdock shell`.

I tried to make a symlink from /bin/bash to /bin/ash but it didn't work. In Alpine, /bin/ash is itself a symlink to /bin/busybox that doesn't recognize the sub-command `bash`.

**Comment by ellmetha** [comment]
Perhaps we could add a `shell` attribute defaulting to `bash` to the `Guest` base class. This attribute could be used by the `Container.shell` method in order to open a shell in the considered container. With this solution the `AlpineGuest` would override the `shell` attribute: `shell = 'ash'`.

**Comment by lingxiaoyang** [comment]
@ellmetha  If everybody agrees on this, do I write `shell = 'ash'` in the code of `AlpineGuest` now, though it's not implemented at this moment?

**Comment by ellmetha** [comment]
Perhaps you could implement it by yourself! :wink:

**Comment by lingxiaoyang** [comment]
@ellmetha @hsoft  Would it work if we change this line: https://github.com/lxdock/lxdock/blame/3fd359902a7ce143309ae626bd0c61c92c6c369a/nomad/container.py#L108

from:
````python
cmd = 'lxc exec {} -- bash'.format(self.lxd_name)
````

to: 
````python
cmd = 'lxc exec {} -- su -m root'.format(self.lxd_name)
````

to support the "native" shell program?
