### ISSUE TITLE
Update docs: unknown command in getting started

### ISSUE THREAD

**Issue by GeoTob** [lxdock/lxdock#43]
Was just going through the getting started doc and came across this snippet:

```bash
$ newgrp lxd
$ sudo lxd init --auto
$ lxc network create lxdbr0 ipv6.address=none ipv4.address=10.0.3.1/24 ipv4.nat=true
$ lxc network attach-profile lxdbr0 default eth0
```

`lxc network` is not a known command in lxc (v2.0.9 from Ubuntu 16.04 repos). I ended up configuring networking through the `lxd init` script. I would submit a PR for the docs, but no idea where `lxc network` comes from and/or what happened to it.. so here's an issue at least:)

**Comment by jaylenw** [comment]
I also encountered the same issue you experienced. I removed lxd and config files and installed lxd using the ppa provided in the guide. I then had no issues with it on Ubuntu 16.04 in regards to "not known command".
