### ISSUE TITLE
create users, no password option

### ISSUE THREAD

**Issue by robvdl** [lxdock/lxdock#44]
If i create users in my lxdock.yml file i can only set the username and home, but not the password.

Will this be added? In the mean time I can set the password in my Ansible playbook but it would be nicer to have this in the lxdock.yml file.

For example vagrant has a default username and password of vagrant, I was reading the source of lxdock and it doesn't look like it is setting any password for users it creates.

**Comment by jaylenw** [comment]
having the option to add a default password in the lxdock.yml file would be useful for me as well.

**Comment by ellmetha** [comment]
This sounds like a great idea. Would you mind submitting a PR for this enhancement? This would be much appreciated! :smiley:

**Comment by robvdl** [comment]
OK that's fine, I have just one question about that.  Should I use sha512 encrypted passwords like Ansible:

http://docs.ansible.com/ansible/user_module.html

Or should I use plaintext password since tools like lxdock and vagrant are generally only used for dev environments anyway.

I am leaning towards sha512 still for correctness, any objections?

**Comment by robvdl** [comment]
Actually it has to be encrypted anyway for useradd, the manpage of useradd and the relevant place in the Ansible source code basically says it:

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/user.py#L352

**Comment by ellmetha** [comment]
@robvdl I think that it would be better if the solution involves encrypted passwords too. :wink:

**Comment by robvdl** [comment]
@ellmetha I have a pr #60 up, it's got a test, even updated the docs, but regardless of writing the test it still failed codecov.

I think the coverage requirements are a bit too stringent, making it very difficult for contributors to get a pr through, even when writing a test for the new functionality.

**Comment by robvdl** [comment]
It looks like this was existing code that was never tested in integration tests, but since I added one line, it was enough to push codecov over the edge and fail the commit.

I guess a project04 could be added with some users to the integration fixtures to get it to go through.

**Comment by robvdl** [comment]
It actually looks like the additional test I can write goes in integration/test_container.py

I am adding a test to the patch now..

**Comment by robvdl** [comment]
@ellmetha pr #60 is passing now

**Comment by ellmetha** [comment]
Support for user passwords was added in 82ae9e0. Thanks @robvdl!
