### ISSUE TITLE
Better user mapping of shared folders

### ISSUE THREAD

**Issue by robvdl** [lxdock/lxdock#46]
The way lxdock handles user mapping on shares "sort of" works, but inside the container the files of a share are still owned by NOBODY and NOGROUP which isn't very useful. Any files created on the share in the container will also be created with a strange UID on the host machine like 10000:10000 which isn't very nice either.

The way I dealt with this using LXD before finding LXDock is like this:

* find out your user id and group on host (e.g. 1000:1000)
* put this into /etc/subuid and /etc/subgid on the host (e.g. echo 'root:1000:1' | sudo tee -a /etc/subuid /etc/subgid)
* Add a disk to the container, and set raw.idmap (e.g. lxc config set containername raw.idmap 'both 1000 1000'

It seems LXDock is taking a different approach using ACLs (which I did not need when using my method), but the end result is not very useful, it just makes the share writable but it doesn't seem to solve user mapping issue properly.

**Comment by hsoft** [comment]
The shared folder situation is a tricky one. I know that the solution we've come up with isn't ideal, but it makes many typical workflow work.

Your approach seems interesting, but doesn't mapping root to an existing user circumvent isolation mechanisms supplied by unprivileged containers (that's a real question, I'm not sure of the answer)? If that's the case, we might as well run our containers with `privileged: true`. That makes the shared folder problem much less problematic.

**Comment by robvdl** [comment]
Thanks for the explanation, I will have a look at privileged container over the weekend I think.

I guess this could be the reason why building deb packages in our container comes up with some sort of strange permission error with fakeroot when I do the user mapping my way... I need to dig a bit deeper into how this all works I think.

**Comment by robvdl** [comment]
Unfortunately I found another issue with the way lxdock does ACL's how you end up with an extra -x permission on each file (whether that is the cause I don't know)... but that does not seem to work well with Python's shutil.copytree() function which basically fails because that calls shutil.copystat which then causes an exception when os.setxattr() is called.

**Comment by hsoft** [comment]
A low tech approach to work around this problem would be to add an option to disable ACL fiddling on shared folders. Then, it would only be a matter of having the user run `chmod -R o=Xrw` on the host and in the guest, set `umask 000` in `/etc/profile` to make sure that files created on the mount from the guest OS are accessible to the host. We would then have a somewhat usable two-way shared folder.

But otherwise, as I wrote earlier, it's a tricky problem...

**Comment by hsoft** [comment]
Here's an interesting, relevant issue: https://github.com/lxc/lxd/issues/2025

**Comment by robvdl** [comment]
You're right, privileged containers has solved my user mapping issue and means I no longer have to put entries into /etc/subgid and /etc/subuid or have to set the raw.idmap on the container.  I had simply misunderstood what privileged containers did and am happy to close this issue for that reason.

The issue building deb files in containers that I had is not an lxdock thing either, it also happens when I create an lxd container by hand, so it's unrelated to lxdock as well.

One thing that could possibly help a little with the user mapping is to allow setting of custom uid and gid when creating container users from the lxdock.yml file, to ensure that the user in the container matches the host user uid/gid... however these uids/gids can't be hard-coded in the lxdock.yaml file either as everyone has a different host user uid/gid it needs to be detected.  For now I have a solution done with Ansible and I am happy enough with how it's working.

**Comment by robvdl** [comment]
Interestingly my issue with building .deb package for our application failing due to a "permission error" during the dh_install step only happens when built from the share itself, not from any other directory.

If I move the source to /tmp, e.g. by doing a "git archive master | tar -x -C /tmp/build; cd /tmp/build; make deb" it works fine.

So it could be something to do with the share, when I do an "ls -l" in /tmp/build the files show normal, when I do it on the share, every file seems to be green (as if it is executable), maybe this is failing deb package builds on the share.

**Comment by hsoft** [comment]
As long as your host and guest UID match (it's usually 1000), you're not going to need any ACL-fiddling in privileged containers, no.

**Comment by robvdl** [comment]
Ok I have solved my issue building deb packages on a share by using privileged containers, then using Ansible to ensure the user in the container has the same uid and gid as the host PC.  This is possible using something like this:

    - name: detecting uid from host machine user
      shell: id -u
      delegate_to: 127.0.0.1
      register: host_user_uid

    - name: detecting gid from host machine user
      shell: id -g
      delegate_to: 127.0.0.1
      register: host_user_gid

And then something like this:

    - name: ensure the foo group gid matches the host user
      group: name=foo gid={{host_user_gid.stdout}}

    - name: ensure the foo user uid matches the host user and has sudo
      user: name=foo uid={{host_user_uid.stdout}} group=foo groups=sudo shell=/bin/bash

I also delete the ubuntu user in my Ansible playbook to ensure there are no uid/gid 1000 conflicts where two users have the same uid/gid.

Now to my main point, after the initial "lxdock up" and provisioning is complete, I have to remove the facl stuff:

    setfacl -bR .

My question is, how can we make this an option in lxdock so that I don't have to get my team to keep doing this every time.

I have come up with two ideas:

1. automatic, as soon as a container is privileged in the lxdock file it never applies facl stuff on any share
2. manual, having an option on each share you can set like "facl: off" to disable it on a per-share basis

I am happy to develop either solution to make this happen if this is OK with the devs.

**Comment by robvdl** [comment]
@hsoft: any ideas about how to go forward adding a feature for completely disabling "set host side ACL" step?  I am particularly interested in doing this for unprivileged containers.

Looking at the source in container.py it will call self._host.give_current_user_access_to_share(source) for both privileged AND unprivileged containers, but not self._host.give_mapped_user_access_to_share(source) which only gets called for privileged containers.

Problem is I don't want ANY of these steps to run for unprivileged containers as the ACLs are getting in my way, how that gets done I don't really care.

I also don't quite get WHY you would want to set host side ACLs for the current user anyway, to me that makes little sense because usually (as you do in vagrant) you make the source of your project available as a share, which is generally already writable to the current user 99.9% of the time anyway.

Could we maybe add an option on a per-share basis to turn off  the set host side ACL step:

shares:
  - source: .
    dest: /src/myproject
    set_host_acl: false

Or what about another solution of detecting whether the folder is writable as the current user first already, and only if it isn't set the host side ACLs?

Either way, I need a solution for this.

**Comment by hsoft** [comment]
A `set_host_acl` option would be a good thing to add, yes.

**Comment by robvdl** [comment]
Coo, I will definitely look into adding the set_host_acl option then if this is the preferred solution, as I really need this feature turned off.

It's not that I want to make things world writable on purpose in this case, it's just that I am using non-privileged containers and 1:1 userid and groupid mapping with the guest user sharing the same uid/gid as the host user.  It's the only way I have been able to build Debian packages inside a container on a share, also it's only a development instance so it doesn't really matter to me anyway.

**Comment by robvdl** [comment]
Created a new PR for this as I for some weird reason it failed to push up after a rebase, so I just created a new new one which is PR #79

**Comment by robvdl** [comment]
PR #79 has been merged from some time now which solved this for me.
