### ISSUE TITLE
Error on lxdock provision

### ISSUE THREAD

**Issue by jaylenw** [lxdock/lxdock#52]
I am having trouble getting my lxc provisioned correctly as every time I run `lxdock provision` i run into the error in the screenshot below.

Error:
![screenshot from 2017-03-25 23-22-07](https://cloud.githubusercontent.com/assets/6505395/24329195/90d638c6-11b3-11e7-9440-1020b9d769cf.png)

After running `lxd init`, and before i run `lxdock provision` this is my lxdock.yml:
![screenshot from 2017-03-25 23-28-32](https://cloud.githubusercontent.com/assets/6505395/24329197/9437e744-11b3-11e7-9355-8605725614b1.png)

LXDock Version:

![screenshot from 2017-03-25 23-30-20](https://cloud.githubusercontent.com/assets/6505395/24329199/95fa8244-11b3-11e7-8331-def76f1f93e7.png)

The system I am using LXDock is Ubuntu 16.04 LTS 64bit

**Comment by hsoft** [comment]
This is related to #51 from yesterday. They fix is to downgrade your ws4py package to v0.3.4

**Comment by jaylenw** [comment]
@hsoft ok thank you. I will close this issue now
