### ISSUE TITLE
lxdock shell does not handle unicode chars but SSHing in does

### ISSUE THREAD

**Issue by robvdl** [lxdock/lxdock#64]
If I go into my container using "lxdock shell" and run my application it fails when printing unicode chars:

UnicodeEncodeError: 'ascii' codec can't encode character '\u0101' in position 696: ordinal not in range(128)

Note this is an exception from my own application, not lxdock itself.

However, if I ssh into the container instead and run the same application, everything works fine.

**Comment by hsoft** [comment]
This is probably a locale problem. If you run `locale`, what do you have in your container, `POSIX`? If that's the case, then there's your problem. It happens (at least that was the case for me) when the host doesn't have the guest's default locale.

For example, in my case, my gentoo host is `en_US.utf-8` and debian's default locale is `en_US.utf8`. I would always end up with a `POSIX` shell.

The solution right now is to specify `LC_ALL` in your `environment` property of the `lxdock.yml`. For example, in one of my project, I have:

```
environment:
  - LC_ALL: en_US.utf8
```

and it does the trick.

**Comment by robvdl** [comment]
Yes this has fixed it thanks, I'm feeling a bit silly because it is mentioned in the docs, appears to be a recent addition I missed.

Closing this because it's mentioned in the docs, and therefore not a bug.
