### ISSUE TITLE
Support LXC "profiles"

### ISSUE THREAD

**Issue by lingxiaoyang** [lxdock/lxdock#68]
When launching an LXC container, it is possible to set up its profiles that can be managed by `lxc profile` command, for example:

```
lxc launch ubuntu-daily:16.04 docker -p default -p docker
```

LXDock should consider supporting this functionality as it's already [here](http://pylxd.readthedocs.io/en/latest/profiles.html) in pylxd. The YAML definition and the management should be further discussed.

**Comment by battlemidget** [comment]
I think this one can be closed?

**Comment by hsoft** [comment]
Hum, yes, I think so. I haven't followed the development of this feature much, but it looks merged...
