### ISSUE TITLE
After upgrade, TypeError for timeout.py

### ISSUE THREAD

**Issue by dtklein** [lxdock/lxdock#81]
I just upgraded ("_sudo pip install lxdock --upgrade_", which upgraded me from lxdock 0.1.1 to 0.2.0), which also upgraded a number of pre-reqs. When I issue "_lxdock status_", "_lxdock up_", "_lxdock halt_", I get the following error message:

  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

The full stack-trace from python is:

david@lxdock:~$ lxdock status
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/lxdock", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/lxdock/cli/main.py", line 244, in main
    LXDock(argv=argv)
  File "/usr/local/lib/python3.5/dist-packages/lxdock/cli/main.py", line 118, in __init__
    getattr(self, args.action)(args)
  File "/usr/local/lib/python3.5/dist-packages/lxdock/cli/main.py", line 207, in status
    self.project.status(container_names=args.name)
  File "/usr/local/lib/python3.5/dist-packages/lxdock/cli/main.py", line 221, in project
    self._project = get_project()
  File "/usr/local/lib/python3.5/dist-packages/lxdock/cli/project.py", line 16, in get_project
    client = get_client()
  File "/usr/local/lib/python3.5/dist-packages/lxdock/client.py", line 6, in get_client
    return pylxd.Client()
  File "/usr/local/lib/python3.5/dist-packages/pylxd/client.py", line 216, in __init__
    response = self.api.get()
  File "/usr/local/lib/python3.5/dist-packages/pylxd/client.py", line 102, in get
    self._api_endpoint, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 526, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 587, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 302, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None.
david@lxdock:~$ 

The system in which I am playing with LXDock is Ubuntu 16.04, x64, running inside Oracle VM VirtualBox 5.1.22, on top of Windows 10 Pro, and using Python 2.7 in the virtual guest.

david@lxdock:~$ python --version
Python 2.7.12
david@lxdock:~$ uname -a
Linux lxdock 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
david@lxdock:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
david@lxdock:~$ pip show lxdock
Name: lxdock
Version: 0.2.0
Summary: LXDock is a tool for orchestrating LXD containers.
Home-page: https://github.com/lxdock/lxdock
Author: Virgil Dupras, Morgan Aubert
Author-email: UNKNOWN
License: GPLv3
Location: /usr/local/lib/python3.5/dist-packages
Requires: PyYAML, pylxd, voluptuous, colorlog
david@lxdock:~$

I am enclosing my lxdock.yml and my provisioning script, in case my lack of understanding is causing this problem (such as a missed or invalid mandatory parm). 

[provision_CA.sh.TXT](https://github.com/lxdock/lxdock/files/1036413/provision_CA.sh.TXT)
[lxdock.yml.TXT](https://github.com/lxdock/lxdock/files/1036414/lxdock.yml.TXT)

Please let me know if there is additional information I need to provide to help diagnose this, and if I am doing things wrong, please point me toward documentation to help me learn to do them right. 

Thanks,

 - dtklein

**Comment by hsoft** [comment]
Thanks for this report. I already had v0.2.0 installed locally, I ran a `pip install -U --user lxdock`, which updated a bunch of dependencies, and I have the same error.

It's probably simply a matter of properly pinning dependencies. I'm looking into it.

**Comment by hsoft** [comment]
On my machine, reverting `requests` to v2.15.1 fixed the problem. Could you confirm? If it's the same on your side, I'd simply pin requests to `<2.16` until we figure out the root cause of the problem.

**Comment by dtklein** [comment]
I removed and reinstalled the python package _requests_ at version 2.15.1


david@lxdock:~$ sudo -H  pip uninstall requests
Uninstalling requests-2.9.1:
  /usr/lib/python3/dist-packages/requests
  /usr/lib/python3/dist-packages/requests-2.9.1.egg-info
Proceed (y/n)? y
  Successfully uninstalled requests-2.9.1
david@lxdock:~$ 
david@lxdock:~$ sudo -H  pip install requests==2.15.1 --upgrade
Collecting requests==2.15.1
  Downloading requests-2.15.1-py2.py3-none-any.whl (558kB)
    100% |████████████████████████████████| 563kB 309kB/s
Installing collected packages: requests
Successfully installed requests-2.15.1
david@lxdock:~$




That seems to have fixed.


david@lxdock:~$ lxdock status
Current container states:
CA0           (stopped)
CA1           (stopped)
david@lxdock:~$





@hsoft Thank you so much for this help. 

Should I submit an enhancement request to nail-up the pre-req for requests at 2.15.1? Is there anything I am supposed to do to help with this? Do you need me to submit a short README with the symptoms and recommended fix in this issue, for submission to the readthedocs webpage (so others can find the cause of their woes more easily than I did) ? 

Also, is there a Beta vs GA version on LXDock, so if people less weirdness tolerant need stability, they can stick to a slower/more stable version which has nailed-up pre-reqs and stuff?

**Comment by hsoft** [comment]
The fix would be to pin `requests` in the `setup.py`. I can do it myself, but since you've reported the issue, if you'd like to make the PR yourself, I see no problem with that. Just make sure that you target the `maint-0.2` branch I've just created.

Also, note that `requests` is a transitive dependency, so it's not currently in `setup.py`, we have to add it (if you dig in `setup.py`'s history, you'll see that we used to pin it for other reasons).

As for beta/release, we already consider lxdock to be of "tech preview" quality. I think it's a bit premature to think too much about stability.

**Comment by hsoft** [comment]
Oh, I was forgetting: of course, the version pinning thing is only the "stopgap" measure. If you're interested in investigating the root cause of the bug, you're also more than welcome to do so. My wild guess is that it's a bug in pylxd, which is the dependency using requests.

**Comment by hsoft** [comment]
Since I haven't heard back from you @dtklein and that the bug is rather severe, I've made the hotfix myself and released a new v0.2.1.

**Comment by dtklein** [comment]
@hsoft I just got to look at this, checked out the maint-0.2 branch and saw you already applied the patch. Thanks. 

I'll try reverting my forced-version installation of requests, upgrading lxdock and see if it works as expected.

Do you want me to reply this issue with the results, or only if it does something weird?

**Comment by hsoft** [comment]
If you can confirm that v0.2.1 works fine on your end, it would be great.

**Comment by dtklein** [comment]
I de-installed requests, did an upgrade of lxdock, I saw it upgraded to 0.2.1, and it put requests 2.15.1. When I ran lxdock commands, they all worked as expected. Thank you so much.
