### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Shark-Linux** [lxdock/lxdock#93]
Curious occurrence appearing in the last release of Shark.  Getting error during install of lxdock 

Collecting lxdock
  Downloading lxdock-0.2.1-py3-none-any.whl (126kB)
Collecting voluptuous<1.0,>=0.9 (from lxdock)
  Downloading voluptuous-0.10.5.tar.gz (41kB)
Collecting requests<2.16,>=2.5.1 (from lxdock)
  Downloading requests-2.15.1-py2.py3-none-any.whl (558kB)
Collecting PyYAML<4.0,>=3.0 (from lxdock)
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting pylxd<3.0,>=2.2 (from lxdock)
  Downloading pylxd-2.2.3.tar.gz (65kB)
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/easy_install-kq_z427m/requests-unixsocket-0.1.5/.eggs/pbr-3.1.1-py3.5.egg
    
    Installed /tmp/pip-build-mm7772i3/pylxd/.eggs/requests_unixsocket-0.1.5-py3.5.egg
    Searching for requests!=2.8.0,>=2.5.2
    Reading https://pypi.python.org/simple/requests/
    Best match: requests 2.18.1
    Downloading https://pypi.python.org/packages/2c/b5/2b6e8ef8dd18203b6399e9f28c7d54f6de7b7549853fe36d575bd31e29a7/requests-2.18.1.tar.gz#md5=40f723ed01dddeaf990d0609d073f021
    Processing requests-2.18.1.tar.gz
    Writing /tmp/easy_install-ltasbn7e/requests-2.18.1/setup.cfg
    Running requests-2.18.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ltasbn7e/requests-2.18.1/egg-dist-tmp-qne4qbj6
    warning: no files found matching 'NOTICE'
    creating /tmp/pip-build-mm7772i3/pylxd/.eggs/requests-2.18.1-py3.5.egg
    Extracting requests-2.18.1-py3.5.egg to /tmp/pip-build-mm7772i3/pylxd/.eggs
    
    Installed /tmp/pip-build-mm7772i3/pylxd/.eggs/requests-2.18.1-py3.5.egg
    Searching for pbr>=1.8
    Reading https://pypi.python.org/simple/pbr/
    Best match: pbr 3.1.1
    Downloading https://pypi.python.org/packages/d5/d6/f2bf137d71e4f213b575faa9eb426a8775732432edb67588a8ee836ecb80/pbr-3.1.1.tar.gz#md5=4e82c2e07af544c56a5b71c801525b00
    Processing pbr-3.1.1.tar.gz
    Writing /tmp/easy_install-ku021efx/pbr-3.1.1/setup.cfg
    Running pbr-3.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ku021efx/pbr-3.1.1/egg-dist-tmp-qhfrm1h1
    creating /tmp/pip-build-mm7772i3/pylxd/.eggs/pbr-3.1.1-py3.5.egg
    Extracting pbr-3.1.1-py3.5.egg to /tmp/pip-build-mm7772i3/pylxd/.eggs
    
    Installed /tmp/pip-build-mm7772i3/pylxd/.eggs/pbr-3.1.1-py3.5.egg
    Searching for urllib3>=1.8
    Reading https://pypi.python.org/simple/urllib3/
    Best match: urllib3 1.21.1
    Downloading https://pypi.python.org/packages/96/d9/40e4e515d3e17ed0adbbde1078e8518f8c4e3628496b56eb8f026a02b9e4/urllib3-1.21.1.tar.gz#md5=ef6c72c79b9c6bcd68c204f9b92abc86
    Processing urllib3-1.21.1.tar.gz
    Writing /tmp/easy_install-8jh5juvi/urllib3-1.21.1/setup.cfg
    Running urllib3-1.21.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8jh5juvi/urllib3-1.21.1/egg-dist-tmp-bxs14euo
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    zip_safe flag not set; analyzing archive contents...
    urllib3.packages.__pycache__.six.cpython-35: module references __path__
    creating /tmp/pip-build-mm7772i3/pylxd/.eggs/urllib3-1.21.1-py3.5.egg
    Extracting urllib3-1.21.1-py3.5.egg to /tmp/pip-build-mm7772i3/pylxd/.eggs
    
    Installed /tmp/pip-build-mm7772i3/pylxd/.eggs/urllib3-1.21.1-py3.5.egg
    Searching for certifi>=2017.4.17
    Reading https://pypi.python.org/simple/certifi/
    Best match: certifi 2017.4.17
    Downloading https://pypi.python.org/packages/dd/0e/1e3b58c861d40a9ca2d7ea4ccf47271d4456ae4294c5998ad817bd1b4396/certifi-2017.4.17.tar.gz#md5=db40445044feda1437ce3ccd5fc28a57
    Processing certifi-2017.4.17.tar.gz
    Writing /tmp/easy_install-wjmxmsmi/certifi-2017.4.17/setup.cfg
    Running certifi-2017.4.17/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wjmxmsmi/certifi-2017.4.17/egg-dist-tmp-q2t39g_8
    /usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '2017.04.17' to '2017.4.17'
      normalized_version,
    zip_safe flag not set; analyzing archive contents...
    certifi.__pycache__.core.cpython-35: module references __file__
    creating /tmp/pip-build-mm7772i3/pylxd/.eggs/certifi-2017.4.17-py3.5.egg
    Extracting certifi-2017.4.17-py3.5.egg to /tmp/pip-build-mm7772i3/pylxd/.eggs
    
    Installed /tmp/pip-build-mm7772i3/pylxd/.eggs/certifi-2017.4.17-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mm7772i3/pylxd/setup.py", line 34, in <module>
        pbr=True)
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1085, in best_match
        dist = working_set.find(req)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 695, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (idna 2.0 (/usr/lib/python3/dist-packages), Requirement.parse('idna<2.6,>=2.5'))
  
I can get it going by manually (after the fail)
pip3 install --upgrade idna 
pip3 install --upgrade chardet
 pip3 install lxdock.

Any idea why this is? I have zero knowledge of pip/python I merely scripted the install as per the docs, which has been working fine until the last ISO. Is there any harm in adding the steps listed above as a workaround until I figure out whats causing the install to fail?

**Comment by lingxiaoyang** [comment]
@Shark-Linux  Thank you for the report! 

The error message should mean that there are two Python packages depending on the `idna` package, but of different versions. That's why it was a "Conflict".

I didn't reproduce the problem during the installation in a python3.5.2 virtualenv on Ubuntu 16.04 LTS. Here are what pip collected at my side:

````
Collecting lxdock
  Downloading lxdock-0.2.1-py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 7.0MB/s 
Collecting requests<2.16,>=2.5.1 (from lxdock)
  Downloading requests-2.15.1-py2.py3-none-any.whl (558kB)
    100% |████████████████████████████████| 563kB 2.5MB/s 
Collecting PyYAML<4.0,>=3.0 (from lxdock)
  Using cached PyYAML-3.12.tar.gz
Collecting pylxd<3.0,>=2.2 (from lxdock)
  Using cached pylxd-2.2.3.tar.gz
Collecting colorlog<3.0,>=2.0 (from lxdock)
  Using cached colorlog-2.10.0-py2.py3-none-any.whl
Collecting voluptuous<1.0,>=0.9 (from lxdock)
  Using cached voluptuous-0.10.5.tar.gz
Collecting pbr>=1.6 (from pylxd<3.0,>=2.2->lxdock)
  Downloading pbr-3.1.1-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 10.6MB/s 
Collecting python-dateutil>=2.4.2 (from pylxd<3.0,>=2.2->lxdock)
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting six>=1.9.0 (from pylxd<3.0,>=2.2->lxdock)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting ws4py!=0.3.5,>=0.3.4 (from pylxd<3.0,>=2.2->lxdock)
  Using cached ws4py-0.4.2.tar.gz
Collecting requests-unixsocket>=0.1.5 (from pylxd<3.0,>=2.2->lxdock)
Collecting cryptography!=1.3.0,>=1.0 (from pylxd<3.0,>=2.2->lxdock)
  Downloading cryptography-1.9.tar.gz (409kB)
    100% |████████████████████████████████| 419kB 3.6MB/s 
Collecting urllib3>=1.8 (from requests-unixsocket>=0.1.5->pylxd<3.0,>=2.2->lxdock)
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Collecting idna>=2.1 (from cryptography!=1.3.0,>=1.0->pylxd<3.0,>=2.2->lxdock)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography!=1.3.0,>=1.0->pylxd<3.0,>=2.2->lxdock)
  Using cached asn1crypto-0.22.0-py2.py3-none-any.whl
Collecting cffi>=1.7 (from cryptography!=1.3.0,>=1.0->pylxd<3.0,>=2.2->lxdock)
  Using cached cffi-1.10.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.7->cryptography!=1.3.0,>=1.0->pylxd<3.0,>=2.2->lxdock)
````

So it seems to me that the `idna 2.0` doesn't come from lxdock. It could be possible that you have previously installed another Python package that depends on `idna 2.0`. That's why you could make it after upgrading the `idna` package.

I think it is necessary to find the pip logs of other packages and to see which one installed `idna 2.0`. Normally, it is necessary to update the version of that package so that it uses the latest dependencies.

**Comment by Shark-Linux** [comment]
Yea. Makes sense I suppose. Just a little baffled this just started happening. I dont have the issue when launching the script when in my cloud but it happens after a fresh install via iso. Python is installed via this script so im not sure where there would be anything preexisting. Adding to my puzzlement is the ISO build previous (and all others before it) worked flawlessly. Im sure you can understand my dilemma. Any advice on where I should look for clues, i.e. logs etc. In the meantime ill run some tests and see if I can pinpoint exactly what scenarios cause this.

**Comment by Shark-Linux** [comment]
Not sure if this makes sense but I solved it.  I simply focused on what changed from previous ISO builds and the current... The issue was eliminated by installing openssh-server.
