### ISSUE TITLE
Allow custom ansible inventory

### ISSUE THREAD

**Issue by emont01** [lxdock/lxdock#98]
I have all my playbooks organized under a folder right next to my lxdock.yml file and it is relatively easy to write and maintain an inventory file but I am unable to tell lxdock to stop using the auto-generated inventory and use my own file so, please! add some way to control if my ansible inventory should be autogenerated or use an existing file instead.

**Comment by hsoft** [comment]
Duplicate to #88. Again, I have nothing against adding this option if it's needed, but I can't imagine a use case. So, I'm curious: what's the use case?

**Comment by emont01** [comment]
Hello @hsoft 

My use case
=========
lxdock assumes an inventory with a list of hosts is enough, my specific use case is the following:

I have servers installed in 2 different locations, they must communicate with each other and they do so using MariaDB master-slave mirrors, however not all places can afford the same number of servers so in one place I have 1 app server and 1 db server and in other only 1 server with both functionalities.

I know I could solve this in various ways but we decided (my team and I) to do the following:

1. Create playbooks that target groups instead of single servers
2. Modify our inventory file to put each server in the corresponding group, namely: app-servers and db-servers, so in one place I have the db server only in db-servers group, but in the other I can add the same server in both groups.
3. Calling ansible from the command line I can run only the necessary playbook and in one go configure all servers in one group the way they have to.

The problem
==========
Is not easy to tell lxdock to:

1. Create containers A, B and C
2. Add server A and C to db-servers group
3. Add server B and C to app-servers group

My current work around is not using provisioning settings in lxdock.yml and configure ansible on my own, then run manually ansible-playbook as many times as necessary. 

Proposed solution
===============
Hopefully I could use something like:

`ANSIBLE_INVENTORY=hosts.ini lxdock up` 
and be done with it because my globally defined provisioner will run only once [1]

[1] [lxdock documentation](https://lxdock.readthedocs.io/en/stable/conf.html) says the following:
> a global ansible provisioner will only run once with an inventory including all containers.

**Comment by hsoft** [comment]
@emont01 have you tried the grouping functionality added in #95? If yes, what exactly is lacking? To me, it should be trivial to add your A, B and C containers to their appropriate groups.

**Comment by emont01** [comment]
@hsoft indeed #95 seems like a solution to my problem, since it was merge days ago I presume is not published on any release yet, right?
Should I try installing from master branch?

**Comment by hsoft** [comment]
@emont01 yes, and yes.
